<?php

namespace Planck\Theme\PlanckBoard\View\Layout;


use Planck\Application;

class LandingPage extends \Planck\View\Layout
{

    public function __construct(Application $application = null)
    {
        parent::__construct($application);

    }


    public function render()
    {
        $html = $this->obInclude(__DIR__.'/template.php');
        $this->setHTML($html, true);
        return parent::render(); // TODO: Change the autogenerated stub
    }

}

